export const mockPatients = [
  {
    id: "p-001",
    firstName: "Amelia",
    lastName: "Rivera",
    gender: "Female",
    birthDate: "1990-03-22",
    phone: "(415) 555-0112",
  },
  {
    id: "p-002",
    firstName: "Noah",
    lastName: "Patel",
    gender: "Male",
    birthDate: "1985-07-18",
    phone: "(415) 555-0174",
  },
  {
    id: "p-003",
    firstName: "Sophia",
    lastName: "Chambers",
    gender: "Female",
    birthDate: "2001-01-10",
    phone: "(415) 555-0158",
  },
  {
    id: "p-004",
    firstName: "Liam",
    lastName: "Nguyen",
    gender: "Male",
    birthDate: "1997-11-02",
    phone: "(415) 555-0142",
  },
];

export const mockAppointments = [
  {
    id: "a-001",
    patient: "Amelia Rivera",
    dentist: "Dr. Emily Carter",
    type: "Routine Checkup",
    date: "2024-04-12",
    time: "09:30",
    room: "Room 2",
    status: "Scheduled",
  },
  {
    id: "a-002",
    patient: "Noah Patel",
    dentist: "Dr. Liam Brooks",
    type: "Root Canal",
    date: "2024-04-12",
    time: "11:00",
    room: "Surgery 1",
    status: "Completed",
  },
  {
    id: "a-003",
    patient: "Sophia Chambers",
    dentist: "Dr. Emily Carter",
    type: "Teeth Whitening",
    date: "2024-04-13",
    time: "13:15",
    room: "Cosmetic",
    status: "Scheduled",
  },
  {
    id: "a-004",
    patient: "Liam Nguyen",
    dentist: "Dr. Blake Howard",
    type: "Emergency",
    date: "2024-04-11",
    time: "15:45",
    room: "Emergency",
    status: "Cancelled",
  },
  {
    id: "a-005",
    patient: "Amelia Rivera",
    dentist: "Dr. Liam Brooks",
    type: "Filling",
    date: "2024-04-10",
    time: "10:00",
    room: "Room 4",
    status: "Completed",
  },
];

export const mockTreatments = [
  {
    id: "t-001",
    name: "Routine Cleaning",
    category: "Preventive",
    duration: 45,
    price: 90,
    description: "Comprehensive cleaning including scaling and polishing.",
  },
  {
    id: "t-002",
    name: "Fluoride Treatment",
    category: "Preventive",
    duration: 20,
    price: 45,
    description: "Strengthens tooth enamel and helps prevent cavities.",
  },
  {
    id: "t-003",
    name: "Root Canal Therapy",
    category: "Restorative",
    duration: 90,
    price: 650,
    description: "Treatment to repair and save a badly decayed tooth.",
  },
  {
    id: "t-004",
    name: "Dental Crown",
    category: "Restorative",
    duration: 75,
    price: 980,
    description: "Custom-made cap to restore shape, size, and appearance.",
  },
  {
    id: "t-005",
    name: "Teeth Whitening",
    category: "Cosmetic",
    duration: 60,
    price: 320,
    description: "In-office whitening treatment for brighter smiles.",
  },
  {
    id: "t-006",
    name: "Dental Veneers",
    category: "Cosmetic",
    duration: 120,
    price: 1400,
    description: "Thin shells placed over teeth to improve appearance.",
  },
];

export const mockInvoices = [
  {
    id: "inv-001",
    patient: "Amelia Rivera",
    treatment: "Routine Cleaning",
    amount: 90,
    status: "Paid",
    issuedOn: "2024-04-05",
    dueOn: "2024-04-12",
  },
  {
    id: "inv-002",
    patient: "Noah Patel",
    treatment: "Root Canal Therapy",
    amount: 650,
    status: "Outstanding",
    issuedOn: "2024-04-02",
    dueOn: "2024-04-16",
  },
  {
    id: "inv-003",
    patient: "Sophia Chambers",
    treatment: "Teeth Whitening",
    amount: 320,
    status: "Paid",
    issuedOn: "2024-03-28",
    dueOn: "2024-04-11",
  },
  {
    id: "inv-004",
    patient: "Liam Nguyen",
    treatment: "Emergency Consultation",
    amount: 180,
    status: "Overdue",
    issuedOn: "2024-03-20",
    dueOn: "2024-03-27",
  },
];
